name: molefocs
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.18
  flutter_svg: ^1.1.1+1
  google_fonts: ^3.0.1
  syncfusion_flutter_pdfviewer: ^20.3.52
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
       - assets/images/home_bg.png
       - assets/images/home_bg.jpg
       - assets/images/home_image1.jpg
       - assets/images/logo.png
       - assets/icons/logo1.png
       - assets/images/icons_focus.png
       - assets/images/icons_listening.png
       - assets/images/icons_reading.png
       - assets/images/icons_speaking.png
       - assets/images/icons_writing.png
       - assets/images/logo1.png
       - assets/images/img_language1.jpg
       - assets/images/img_language2.jpg
       - assets/images/img_language3.jpg
       - assets/images/img_language4.jpg
       - assets/images/img_language5.png
       - assets/images/img_language6.jpg
       - assets/images/img_language7.jpg
       - assets/images/img_listening1.jpg
       - assets/images/img_listening2.jpg
       - assets/images/img_listening3.jpg
       - assets/images/img_listening4.jpg
       - assets/images/img_listening5.jpg
       - assets/images/img_listening6.jpg
       - assets/images/img_listening7.jpg
       - assets/images/img_reading1.jpg
       - assets/images/img_reading2.jpg
       - assets/images/img_reading3.jpg
       - assets/images/img_reading4.png
       - assets/images/img_reading5.png
       - assets/images/img_reading6.jpg
       - assets/images/img_reading7.jpg
       - assets/images/img_writing1.jpg
       - assets/images/img_writing2.jpg
       - assets/images/img_writing3.jpg
       - assets/images/img_writing4.jpg
       - assets/images/img_writing5.jpg
       - assets/images/img_writing6.jpg
       - assets/images/img_writing7.jpg
       - assets/images/img_speaking1.jpg
       - assets/images/img_speaking2.png
       - assets/images/img_speaking3.jpg
       - assets/images/img_speaking4.png
       - assets/images/img_speaking5.jpg
       - assets/images/img_speaking6.jpg
       - assets/images/img_speaking7.jpg
       - assets/pdf/langfoc1.pdf
       - assets/pdf/langfoc2.pdf
       - assets/pdf/langfoc3.pdf
       - assets/pdf/langfoc4.pdf
       - assets/pdf/langfoc5.pdf
       - assets/pdf/langfoc6.pdf
       - assets/pdf/langfoc7.pdf
       - assets/pdf/listening1.pdf
       - assets/pdf/listening2.pdf
       - assets/pdf/listening3.pdf
       - assets/pdf/listening4.pdf
       - assets/pdf/listening5.pdf
       - assets/pdf/listening6.pdf
       - assets/pdf/listening7.pdf
       - assets/audio/unit_1.mp3
       - assets/audio/unit_2.mp3
       - assets/audio/unit_3.mp3
       - assets/audio/unit_4.mp3
       - assets/audio/unit_5.mp3
       - assets/audio/unit_6.mp3
       - assets/audio/unit_7.mp3
       - assets/pdf/reading1.pdf
       - assets/pdf/reading2.pdf
       - assets/pdf/reading3.pdf
       - assets/pdf/reading4.pdf
       - assets/pdf/reading5.pdf
       - assets/pdf/reading6.pdf
       - assets/pdf/reading7.pdf
       - assets/pdf/speaking1.pdf
       - assets/pdf/speaking2.pdf
       - assets/pdf/speaking3.pdf
       - assets/pdf/speaking4.pdf
       - assets/pdf/speaking5.pdf
       - assets/pdf/speaking6.pdf
       - assets/pdf/speaking7.pdf
       - assets/pdf/writing1.pdf
       - assets/pdf/writing2.pdf
       - assets/pdf/writing3.pdf
       - assets/pdf/writing4.pdf
       - assets/pdf/writing5.pdf
       - assets/pdf/writing6.pdf
       - assets/pdf/writing7.pdf
 
 
  fonts:
      - family: Montserrat Regular
        fonts:
          - asset: assets/fonts/mo_re.ttf

      - family: Montserrat Medium
        fonts:
          - asset: assets/fonts/mo_me.ttf
      
      - family: OpenSans Regular
        fonts:
          - asset: assets/fonts/opensans-regular.ttf

      - family: OpenSans Bold
        fonts:
          - asset: assets/fonts/opensans-bold.ttf
  
