name: molefocs
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.18
  flutter_svg: ^1.1.1+1
  google_fonts: ^3.0.1
  syncfusion_flutter_pdfviewer: ^20.2.43-beta
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
       - assets/images/logo.png
       - assets/images/home_bg.png
       - assets/images/home_bg.jpg
       - assets/images/home_image1.jpg
       - assets/images/logo.png
       - assets/images/logo1.png
       - assets/images/img_speaking1.jpg
       - assets/images/img_speaking2.jpg
       - assets/images/img_speaking3.jpg
       - assets/images/img_speaking4.jpg
       - assets/images/img_speaking5.jpg
       - assets/images/img_speaking6.jpg
       - assets/images/img_speaking7.jpg
       - assets/pdf/langfoc1.pdf
       - assets/pdf/listening1.pdf
       - assets/pdf/listening2.pdf
       - assets/pdf/listening3.pdf
       - assets/pdf/listening4.pdf
       - assets/pdf/listening5.pdf
       - assets/pdf/listening6.pdf
       - assets/pdf/listening7.pdf
       - assets/pdf/reading1.pdf
       - assets/pdf/reading3.pdf
       - assets/pdf/reading4.pdf
       - assets/pdf/reading5.pdf
       - assets/pdf/reading6.pdf
       - assets/pdf/speaking1.pdf
       - assets/pdf/speaking2.pdf
       - assets/pdf/speaking3.pdf
       - assets/pdf/speaking4.pdf
       - assets/pdf/speaking5.pdf
       - assets/pdf/speaking6.pdf
       - assets/pdf/speaking7.pdf
       - assets/pdf/writing1.pdf
 
 
  fonts:
      - family: Montserrat Regular
        fonts:
          - asset: assets/fonts/mo_re.ttf

      - family: Montserrat Medium
        fonts:
          - asset: assets/fonts/mo_me.ttf
      
      - family: OpenSans Regular
        fonts:
          - asset: assets/fonts/opensans-regular.ttf

      - family: OpenSans Bold
        fonts:
          - asset: assets/fonts/opensans-bold.ttf
  
